# Generated by Django 4.0.7 on 2026-01-14 16:32

import django.core.validators
from django.db import migrations, models
import sample_label.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SampleBarcode',
            fields=[
                ('modified_datetime', models.DateTimeField(auto_now=True, null=True, verbose_name='Modified DateTime')),
                ('created_datetime', models.DateTimeField(auto_now_add=True, verbose_name='Created DateTime')),
                ('sample_barcode_id', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='Sample Barcode ID')),
                ('barcode_slug', models.CharField(max_length=255, verbose_name='Sample Barcode Slug')),
                ('in_freezer', models.CharField(choices=[(None, '(Unknown)'), ('no', 'No'), ('yes', 'Yes')], default='no', max_length=3, verbose_name='In Freezer')),
                ('storage_location', models.CharField(blank=True, max_length=255, null=True, verbose_name='Storage Location')),
                ('sample_year', models.PositiveIntegerField(default=sample_label.models.current_year, validators=[django.core.validators.MinValueValidator(1988)], verbose_name='Sample Year')),
                ('purpose', models.CharField(blank=True, max_length=255, null=True, verbose_name='Sample Barcode Purpose')),
            ],
            options={
                'verbose_name': 'SampleBarcode',
                'verbose_name_plural': 'Sample Barcodes',
            },
        ),
        migrations.CreateModel(
            name='SampleLabelRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified_datetime', models.DateTimeField(auto_now=True, null=True, verbose_name='Modified DateTime')),
                ('created_datetime', models.DateTimeField(auto_now_add=True, verbose_name='Created DateTime')),
                ('sample_year', models.PositiveIntegerField(default=sample_label.models.current_year, validators=[django.core.validators.MinValueValidator(1988)], verbose_name='Sample Year')),
                ('purpose', models.CharField(max_length=255, verbose_name='Sample Label Purpose')),
                ('sample_label_prefix', models.CharField(max_length=12, verbose_name='Sample Label Prefix')),
                ('req_sample_label_num', models.IntegerField(default=1, verbose_name='Number Requested')),
                ('min_sample_label_num', models.IntegerField(default=1)),
                ('max_sample_label_num', models.IntegerField(default=1)),
                ('min_sample_label_id', models.CharField(max_length=17, verbose_name='Min Sample Label ID')),
                ('max_sample_label_id', models.CharField(max_length=17, verbose_name='Max Sample Label ID')),
                ('sample_label_request_slug', models.SlugField(max_length=255, verbose_name='Sample Label Request Slug')),
            ],
            options={
                'verbose_name': 'SampleLabelRequest',
                'verbose_name_plural': 'Sample Label Requests',
            },
        ),
        migrations.CreateModel(
            name='SampleMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified_datetime', models.DateTimeField(auto_now=True, null=True, verbose_name='Modified DateTime')),
                ('created_datetime', models.DateTimeField(auto_now_add=True, verbose_name='Created DateTime')),
                ('sample_material_code', models.CharField(max_length=1, unique=True, verbose_name='Sample Material Code')),
                ('sample_material_label', models.CharField(max_length=255, verbose_name='Sample Material Label')),
            ],
            options={
                'verbose_name': 'Sample Material',
                'verbose_name_plural': 'Sample Materials',
            },
        ),
        migrations.CreateModel(
            name='SampleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified_datetime', models.DateTimeField(auto_now=True, null=True, verbose_name='Modified DateTime')),
                ('created_datetime', models.DateTimeField(auto_now_add=True, verbose_name='Created DateTime')),
                ('sample_type_code', models.CharField(max_length=2, unique=True, verbose_name='Sample Type Code')),
                ('sample_type_label', models.CharField(max_length=255, verbose_name='Sample Type Label')),
            ],
            options={
                'verbose_name': 'Sample Type',
                'verbose_name_plural': 'Sample Types',
            },
        ),
    ]
