# Generated by Django 4.0.7 on 2026-01-14 16:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import sample_label.models
import utility.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('field_site', '0002_initial'),
        ('sample_label', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sampletype',
            name='created_by',
            field=models.ForeignKey(default=utility.models.get_default_user, on_delete=models.SET(utility.models.get_sentinel_user), to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='samplematerial',
            name='created_by',
            field=models.ForeignKey(default=utility.models.get_default_user, on_delete=models.SET(utility.models.get_sentinel_user), to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='samplelabelrequest',
            name='created_by',
            field=models.ForeignKey(default=utility.models.get_default_user, on_delete=models.SET(utility.models.get_sentinel_user), to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='samplelabelrequest',
            name='sample_material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='sample_label.samplematerial'),
        ),
        migrations.AddField(
            model_name='samplelabelrequest',
            name='sample_type',
            field=models.ForeignKey(default=sample_label.models.get_unassigned_sample_type, on_delete=django.db.models.deletion.RESTRICT, to='sample_label.sampletype'),
        ),
        migrations.AddField(
            model_name='samplelabelrequest',
            name='site_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='field_site.fieldsite'),
        ),
        migrations.AddField(
            model_name='samplebarcode',
            name='created_by',
            field=models.ForeignKey(default=utility.models.get_default_user, on_delete=models.SET(utility.models.get_sentinel_user), to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='samplebarcode',
            name='sample_label_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sample_label.samplelabelrequest'),
        ),
        migrations.AddField(
            model_name='samplebarcode',
            name='sample_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sample_label.sampletype'),
        ),
        migrations.AddField(
            model_name='samplebarcode',
            name='site_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='field_site.fieldsite'),
        ),
    ]
