# Generated by Django 4.0.7 on 2026-01-14 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Freezer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified_datetime', models.DateTimeField(auto_now=True, null=True, verbose_name='Modified DateTime')),
                ('created_datetime', models.DateTimeField(auto_now_add=True, verbose_name='Created DateTime')),
                ('freezer_label', models.CharField(max_length=255, unique=True, verbose_name='Freezer Label')),
                ('freezer_label_slug', models.SlugField(max_length=255, verbose_name='Freezer Label Slug')),
                ('freezer_room_name', models.CharField(max_length=255, verbose_name='Freezer Room Name')),
                ('freezer_depth', models.DecimalField(decimal_places=10, max_digits=15, verbose_name='Freezer Depth')),
                ('freezer_length', models.DecimalField(decimal_places=10, max_digits=15, verbose_name='Freezer Length')),
                ('freezer_width', models.DecimalField(decimal_places=10, max_digits=15, verbose_name='Freezer Width')),
                ('freezer_dimension_units', models.CharField(choices=[(None, '(Unknown)'), ('meter', 'Meter (m)'), ('centimeter', 'Centimeters (cm)'), ('feet', 'Feet (ft)'), ('inch', 'Inches (in)')], max_length=50, verbose_name='Freezer Dimensions Units')),
                ('freezer_capacity_columns', models.PositiveIntegerField(verbose_name='Freezer Column Capacity (Boxes)')),
                ('freezer_capacity_rows', models.PositiveIntegerField(verbose_name='Freezer Row Capacity (Boxes)')),
                ('freezer_capacity_depth', models.PositiveIntegerField(verbose_name='Freezer Depth Capacity (Boxes)')),
                ('freezer_rated_temp', models.IntegerField(verbose_name='Rated Freezer Temperature')),
                ('freezer_rated_temp_units', models.CharField(choices=[('fahrenheit', 'Fahrenheit'), ('celsius', 'Celsius'), ('kelvin', 'Kelvin')], max_length=50, verbose_name='Rated Freezer Temperature Units')),
            ],
            options={
                'verbose_name': 'Freezer',
                'verbose_name_plural': 'Freezers',
            },
        ),
        migrations.CreateModel(
            name='FreezerBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified_datetime', models.DateTimeField(auto_now=True, null=True, verbose_name='Modified DateTime')),
                ('created_datetime', models.DateTimeField(auto_now_add=True, verbose_name='Created DateTime')),
                ('freezer_box_label', models.CharField(max_length=255, unique=True, verbose_name='Freezer Box Label')),
                ('freezer_box_label_slug', models.SlugField(max_length=255, verbose_name='Freezer Box Label Slug')),
                ('freezer_box_column', models.PositiveIntegerField(verbose_name='Freezer Box Column')),
                ('freezer_box_row', models.PositiveIntegerField(verbose_name='Freezer Box Row')),
                ('freezer_box_depth', models.PositiveIntegerField(verbose_name='Freezer Box Depth')),
                ('freezer_box_capacity_column', models.PositiveIntegerField(verbose_name='Box Column Capacity (Inventory)')),
                ('freezer_box_capacity_row', models.PositiveIntegerField(verbose_name='Box Row Capacity (Inventory)')),
            ],
            options={
                'verbose_name': 'Freezer Box',
                'verbose_name_plural': 'Freezer Boxes',
            },
        ),
        migrations.CreateModel(
            name='FreezerInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified_datetime', models.DateTimeField(auto_now=True, null=True, verbose_name='Modified DateTime')),
                ('created_datetime', models.DateTimeField(auto_now_add=True, verbose_name='Created DateTime')),
                ('freezer_inventory_slug', models.SlugField(max_length=27, unique=True, verbose_name='Freezer Inventory Slug')),
                ('freezer_inventory_type', models.CharField(choices=[('filter', 'Filter'), ('subcore', 'SubCore'), ('extraction', 'Extraction'), ('pooled_lib', 'Pooled Library')], max_length=50, verbose_name='Freezer Inventory Type')),
                ('freezer_inventory_status', models.CharField(choices=[('in', 'In Stock'), ('out', 'Checked Out'), ('perm_removed', 'Permanently Removed')], default='in', max_length=50, verbose_name='Freezer Inventory Status')),
                ('freezer_inventory_loc_status', models.CharField(choices=[('empty', 'Empty'), ('filled', 'Filled')], default='filled', max_length=50, verbose_name='Freezer Inventory Location Status')),
                ('freezer_inventory_freeze_datetime', models.DateTimeField(blank=True, null=True, verbose_name='First Freeze DateTime')),
                ('freezer_inventory_column', models.PositiveIntegerField(verbose_name='Freezer Box Column')),
                ('freezer_inventory_row', models.PositiveIntegerField(verbose_name='Freezer Box Row')),
            ],
            options={
                'verbose_name': 'Freezer Inventory',
                'verbose_name_plural': 'Freezer Inventory',
            },
        ),
        migrations.CreateModel(
            name='FreezerInventoryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified_datetime', models.DateTimeField(auto_now=True, null=True, verbose_name='Modified DateTime')),
                ('created_datetime', models.DateTimeField(auto_now_add=True, verbose_name='Created DateTime')),
                ('freezer_log_slug', models.SlugField(max_length=255, verbose_name='Inventory Log Slug')),
                ('freezer_log_action', models.CharField(choices=[('checkout', 'Checkout'), ('return', 'Return'), ('perm_removed', 'Permanent Removal')], max_length=50, verbose_name='Inventory Log Action')),
                ('freezer_log_notes', models.TextField(blank=True, verbose_name='Inventory Log Notes')),
            ],
            options={
                'verbose_name': 'Inventory Log',
                'verbose_name_plural': 'Inventory Logs',
            },
        ),
        migrations.CreateModel(
            name='FreezerRack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified_datetime', models.DateTimeField(auto_now=True, null=True, verbose_name='Modified DateTime')),
                ('created_datetime', models.DateTimeField(auto_now_add=True, verbose_name='Created DateTime')),
                ('freezer_rack_label', models.CharField(max_length=255, unique=True, verbose_name='Freezer Rack Label')),
                ('freezer_rack_label_slug', models.SlugField(max_length=255, verbose_name='Freezer Rack Label Slug')),
                ('freezer_rack_column_start', models.PositiveIntegerField(verbose_name='Freezer Rack Column Start')),
                ('freezer_rack_column_end', models.PositiveIntegerField(verbose_name='Freezer Rack Column End')),
                ('freezer_rack_row_start', models.PositiveIntegerField(verbose_name='Freezer Rack Row Start')),
                ('freezer_rack_row_end', models.PositiveIntegerField(verbose_name='Freezer Rack Row End')),
                ('freezer_rack_depth_start', models.PositiveIntegerField(verbose_name='Freezer Rack Depth Start')),
                ('freezer_rack_depth_end', models.PositiveIntegerField(verbose_name='Freezer Rack Depth End')),
            ],
            options={
                'verbose_name': 'Freezer Rack',
                'verbose_name_plural': 'Freezer Racks',
            },
        ),
        migrations.CreateModel(
            name='ReturnAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified_datetime', models.DateTimeField(auto_now=True, null=True, verbose_name='Modified DateTime')),
                ('created_datetime', models.DateTimeField(auto_now_add=True, verbose_name='Created DateTime')),
                ('action_code', models.CharField(max_length=255, unique=True, verbose_name='Action Code')),
                ('action_label', models.CharField(max_length=255, verbose_name='Action Label')),
            ],
            options={
                'verbose_name': 'Return Action',
                'verbose_name_plural': 'Return Actions',
            },
        ),
        migrations.CreateModel(
            name='FreezerInventoryReturnMetadata',
            fields=[
                ('modified_datetime', models.DateTimeField(auto_now=True, null=True, verbose_name='Modified DateTime')),
                ('created_datetime', models.DateTimeField(auto_now_add=True, verbose_name='Created DateTime')),
                ('freezer_log', models.OneToOneField(limit_choices_to={'freezer_log_action': 'return'}, on_delete=django.db.models.deletion.RESTRICT, primary_key=True, related_name='freezer_return_metadata', serialize=False, to='freezer_inventory.freezerinventorylog')),
                ('freezer_return_slug', models.SlugField(max_length=255, verbose_name='Return Slug')),
                ('freezer_return_metadata_entered', models.CharField(choices=[(None, '(Unknown)'), ('no', 'No'), ('yes', 'Yes')], default='no', max_length=3, verbose_name='Metadata Entered')),
                ('freezer_return_vol_taken', models.DecimalField(blank=True, decimal_places=10, max_digits=15, null=True, verbose_name='Volume Taken')),
                ('freezer_return_vol_units', models.CharField(blank=True, choices=[(None, '(Unknown)'), ('microliter', 'microliter (µL)'), ('milliliter', 'milliliter (mL)')], max_length=50, verbose_name='Volume Units')),
                ('freezer_return_notes', models.TextField(blank=True, verbose_name='Return Notes')),
            ],
            options={
                'verbose_name': 'Inventory Return Metadata',
                'verbose_name_plural': 'Inventory Return Metadata',
            },
        ),
    ]
