# Generated by Django 4.0.7 on 2026-01-14 16:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import utility.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sample_label', '0001_initial'),
        ('freezer_inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='returnaction',
            name='created_by',
            field=models.ForeignKey(default=utility.models.get_default_user, on_delete=models.SET(utility.models.get_sentinel_user), to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='freezerrack',
            name='created_by',
            field=models.ForeignKey(default=utility.models.get_default_user, on_delete=models.SET(utility.models.get_sentinel_user), to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='freezerrack',
            name='freezer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='freezer', to='freezer_inventory.freezer'),
        ),
        migrations.AddField(
            model_name='freezerinventorylog',
            name='created_by',
            field=models.ForeignKey(default=utility.models.get_default_user, on_delete=models.SET(utility.models.get_sentinel_user), to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='freezerinventorylog',
            name='freezer_inventory',
            field=models.ForeignKey(limit_choices_to={'freezer_inventory_loc_status': 'filled'}, on_delete=django.db.models.deletion.RESTRICT, related_name='freezer_inventory_logs', to='freezer_inventory.freezerinventory'),
        ),
        migrations.AddField(
            model_name='freezerinventory',
            name='created_by',
            field=models.ForeignKey(default=utility.models.get_default_user, on_delete=models.SET(utility.models.get_sentinel_user), to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='freezerinventory',
            name='freezer_box',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='freezer_box', to='freezer_inventory.freezerbox'),
        ),
        migrations.AddField(
            model_name='freezerinventory',
            name='sample_barcode',
            field=models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to='sample_label.samplebarcode'),
        ),
        migrations.AddField(
            model_name='freezerbox',
            name='created_by',
            field=models.ForeignKey(default=utility.models.get_default_user, on_delete=models.SET(utility.models.get_sentinel_user), to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='freezerbox',
            name='freezer_rack',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='freezer_rack', to='freezer_inventory.freezerrack'),
        ),
        migrations.AddField(
            model_name='freezer',
            name='created_by',
            field=models.ForeignKey(default=utility.models.get_default_user, on_delete=models.SET(utility.models.get_sentinel_user), to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='freezerrack',
            unique_together={('freezer', 'freezer_rack_column_start', 'freezer_rack_column_end', 'freezer_rack_row_start', 'freezer_rack_row_end', 'freezer_rack_depth_start', 'freezer_rack_depth_end')},
        ),
        migrations.AddField(
            model_name='freezerinventoryreturnmetadata',
            name='created_by',
            field=models.ForeignKey(default=utility.models.get_default_user, on_delete=models.SET(utility.models.get_sentinel_user), to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='freezerinventoryreturnmetadata',
            name='freezer_return_actions',
            field=models.ManyToManyField(blank=True, related_name='freezer_return_actions', to='freezer_inventory.returnaction', verbose_name='Return Action(s)'),
        ),
        migrations.AlterUniqueTogether(
            name='freezerinventory',
            unique_together={('freezer_box', 'freezer_inventory_column', 'freezer_inventory_row', 'freezer_inventory_loc_status')},
        ),
        migrations.AlterUniqueTogether(
            name='freezerbox',
            unique_together={('freezer_rack', 'freezer_box_column', 'freezer_box_row', 'freezer_box_depth')},
        ),
    ]
