# Generated by Django 4.0.7 on 2026-01-14 16:32

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnvMeasure',
            fields=[
                ('modified_datetime', models.DateTimeField(auto_now=True, null=True, verbose_name='Modified DateTime')),
                ('created_datetime', models.DateTimeField(auto_now_add=True, verbose_name='Created DateTime')),
                ('env_global_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='EnvMeas Global ID')),
                ('env_measure_datetime', models.DateTimeField(auto_now=True, verbose_name='Measurement DateTime')),
                ('env_instrument', models.TextField(blank=True, choices=[(None, '(Unknown)'), ('env_ctd', 'CTD'), ('env_ysi', 'YSI'), ('env_secchi', 'Secchi Disk'), ('env_niskin', 'Niskin'), ('env_inst_other', 'Other')], verbose_name='Instruments Used')),
                ('env_measure_value', models.CharField(blank=True, max_length=255, verbose_name='Value')),
                ('env_measure_notes', models.TextField(blank=True, verbose_name='Measurement Notes')),
            ],
            options={
                'verbose_name': 'Env Measurement',
                'verbose_name_plural': 'Env Measurements',
            },
        ),
        migrations.CreateModel(
            name='EnvMeasureType',
            fields=[
                ('modified_datetime', models.DateTimeField(auto_now=True, null=True, verbose_name='Modified DateTime')),
                ('created_datetime', models.DateTimeField(auto_now_add=True, verbose_name='Created DateTime')),
                ('env_measure_uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='EnvMeasure UUID')),
                ('env_measure_type_code', models.CharField(max_length=255, unique=True, verbose_name='Measure Code')),
                ('env_measure_type_unit', models.CharField(max_length=255, verbose_name='Measure Unit')),
                ('env_measure_type_name', models.SlugField(max_length=255, verbose_name='Measure Name')),
            ],
            options={
                'verbose_name': 'Env Measure Type',
                'verbose_name_plural': 'Env Measure Types',
            },
        ),
        migrations.CreateModel(
            name='FieldCrew',
            fields=[
                ('modified_datetime', models.DateTimeField(auto_now=True, null=True, verbose_name='Modified DateTime')),
                ('created_datetime', models.DateTimeField(auto_now_add=True, verbose_name='Created DateTime')),
                ('crew_global_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Crew Global ID')),
                ('crew_fname', models.CharField(blank=True, max_length=255, verbose_name='Crew First Name')),
                ('crew_lname', models.CharField(blank=True, max_length=255, verbose_name='Crew Last Name')),
            ],
            options={
                'verbose_name': 'Field Crew',
                'verbose_name_plural': 'Field Crew',
            },
        ),
        migrations.CreateModel(
            name='FieldSample',
            fields=[
                ('modified_datetime', models.DateTimeField(auto_now=True, null=True, verbose_name='Modified DateTime')),
                ('created_datetime', models.DateTimeField(auto_now_add=True, verbose_name='Created DateTime')),
                ('sample_global_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Sample Global ID')),
                ('sample_code', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Sample Code')),
                ('sample_datetime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Sample DateTime')),
                ('barcode_slug', models.SlugField(max_length=255, verbose_name='Field Sample Barcode Slug')),
                ('is_extracted', models.CharField(choices=[(None, '(Unknown)'), ('no', 'No'), ('yes', 'Yes')], default='no', max_length=3, verbose_name='Extracted')),
                ('sampling_method', models.CharField(blank=True, choices=[(None, '(Unknown)'), ('hand', 'By Hand'), ('plankton_net', 'Plankton Net')], max_length=255, verbose_name='Sampling Method')),
            ],
            options={
                'verbose_name': 'Field Sample',
                'verbose_name_plural': 'Field Samples',
            },
        ),
        migrations.CreateModel(
            name='FieldSurvey',
            fields=[
                ('modified_datetime', models.DateTimeField(auto_now=True, null=True, verbose_name='Modified DateTime')),
                ('created_datetime', models.DateTimeField(auto_now_add=True, verbose_name='Created DateTime')),
                ('survey_global_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Survey Global ID')),
                ('survey_code', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Survey Code')),
                ('survey_datetime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Survey DateTime')),
                ('recorder_fname', models.CharField(blank=True, max_length=255, verbose_name='Recorder First Name')),
                ('recorder_lname', models.CharField(blank=True, max_length=255, verbose_name='Recorder Last Name')),
                ('env_measure_mode', models.CharField(blank=True, choices=[(None, '(Unknown)'), ('on_foot', 'On Foot'), ('on_boat', 'Boat')], max_length=50, verbose_name='Collection Mode')),
                ('survey_complete', models.CharField(blank=True, choices=[(None, '(Unknown)'), ('no', 'No'), ('yes', 'Yes')], max_length=50, verbose_name='Survey Complete')),
                ('gps_alt', models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True, verbose_name='GPS Altitude (m)')),
            ],
            options={
                'verbose_name': 'Field Survey',
                'verbose_name_plural': 'Field Surveys',
            },
        ),
        migrations.CreateModel(
            name='FilterSample',
            fields=[
                ('modified_datetime', models.DateTimeField(auto_now=True, null=True, verbose_name='Modified DateTime')),
                ('created_datetime', models.DateTimeField(auto_now_add=True, verbose_name='Created DateTime')),
                ('field_sample', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='filter_sample', serialize=False, to='field_survey.fieldsample')),
                ('is_prefilter', models.CharField(blank=True, choices=[(None, '(Unknown)'), ('no', 'No'), ('yes', 'Yes')], max_length=50, verbose_name='Prefilter')),
                ('filter_fname', models.CharField(blank=True, max_length=255, verbose_name='Filterer First Name')),
                ('filter_lname', models.CharField(blank=True, max_length=255, verbose_name='Filterer Last Name')),
                ('filter_datetime', models.DateTimeField(blank=True, null=True, verbose_name='Filter DateTime')),
                ('filter_method', models.CharField(blank=True, choices=[(None, '(Unknown)'), ('vacuum', 'Vacuum'), ('gravity', 'Gravity'), ('peristaltic', 'Peristaltic'), ('other', 'Other')], max_length=50, verbose_name='Filter Method')),
                ('filter_method_other', models.CharField(blank=True, max_length=255, verbose_name='Other Filter Method')),
                ('filter_vol', models.DecimalField(blank=True, decimal_places=10, max_digits=15, null=True, verbose_name='Water Volume Filtered')),
                ('filter_type', models.CharField(blank=True, choices=[(None, '(Unknown)'), ('nitex', 'Nitex'), ('gff', 'Glass Fiber Filter (GF/F)'), ('supor', 'Supor'), ('cn', 'Cellulose Nitrate (CN)'), ('other', 'Other')], max_length=50, verbose_name='Filter Type')),
                ('filter_type_other', models.CharField(blank=True, max_length=255, verbose_name='Other Filter Type')),
                ('filter_pore', models.DecimalField(blank=True, decimal_places=10, max_digits=15, null=True, verbose_name='Filter Pore Size')),
                ('filter_size', models.DecimalField(blank=True, decimal_places=10, max_digits=15, null=True, verbose_name='Filter Size')),
                ('filter_saturation', models.BooleanField(blank=True, null=True, verbose_name='Saturation')),
                ('filter_notes', models.TextField(blank=True, verbose_name='Filter Notes')),
            ],
            options={
                'verbose_name': 'Filter Sample',
                'verbose_name_plural': 'Filter Samples',
            },
        ),
        migrations.CreateModel(
            name='SubCoreSample',
            fields=[
                ('modified_datetime', models.DateTimeField(auto_now=True, null=True, verbose_name='Modified DateTime')),
                ('created_datetime', models.DateTimeField(auto_now_add=True, verbose_name='Created DateTime')),
                ('field_sample', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='subcore_sample', serialize=False, to='field_survey.fieldsample')),
                ('subcore_fname', models.CharField(blank=True, max_length=255, verbose_name='Sub-Corer First Name')),
                ('subcore_lname', models.CharField(blank=True, max_length=255, verbose_name='Sub-Corer Last Name')),
                ('subcore_sample_label', models.CharField(blank=True, max_length=255, verbose_name='Sub-Core Sample Label')),
                ('subcore_method', models.CharField(blank=True, choices=[(None, '(Unknown)'), ('slices', 'Slices'), ('syringe', 'Syringe'), ('other', 'Other')], max_length=50, verbose_name='Sub-Core Method')),
                ('subcore_method_other', models.CharField(blank=True, max_length=255, verbose_name='Other Sub-Core Method')),
                ('subcore_datetime_start', models.DateTimeField(blank=True, null=True, verbose_name='Sub-Core DateTime Start')),
                ('subcore_datetime_end', models.DateTimeField(blank=True, null=True, verbose_name='Sub-Core DateTime End')),
                ('subcore_number', models.IntegerField(blank=True, null=True, verbose_name='Number of Sub-Cores')),
                ('subcore_length', models.DecimalField(blank=True, decimal_places=10, max_digits=15, null=True, verbose_name='Sub-Core Length (cm)')),
                ('subcore_diameter', models.DecimalField(blank=True, decimal_places=10, max_digits=15, null=True, verbose_name='Sub-Core Diameter (cm)')),
                ('subcore_clayer', models.IntegerField(blank=True, null=True, verbose_name='Sub-Core Consistency Layer')),
                ('subcore_notes', models.TextField(blank=True, verbose_name='Sub-Core Notes')),
            ],
            options={
                'verbose_name': 'SubCore Sample',
                'verbose_name_plural': 'SubCore Samples',
            },
        ),
    ]
