# Generated by Django 4.0.7 on 2026-01-14 16:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import utility.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('utility', '0001_initial'),
        ('field_site', '0002_initial'),
        ('sample_label', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('field_survey', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldsurvey',
            name='created_by',
            field=models.ForeignKey(default=utility.models.get_default_user, on_delete=models.SET(utility.models.get_sentinel_user), to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fieldsurvey',
            name='project_ids',
            field=models.ManyToManyField(related_name='project_ids', to='utility.project', verbose_name='Affiliated Project(s)'),
        ),
        migrations.AddField(
            model_name='fieldsurvey',
            name='site_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='field_site.fieldsite'),
        ),
        migrations.AddField(
            model_name='fieldsurvey',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET(utility.models.get_sentinel_user), related_name='supervisor', to=settings.AUTH_USER_MODEL, verbose_name='Supervisor'),
        ),
        migrations.AddField(
            model_name='fieldsurvey',
            name='username',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET(utility.models.get_sentinel_user), related_name='username', to=settings.AUTH_USER_MODEL, verbose_name='Username'),
        ),
        migrations.AddField(
            model_name='fieldsample',
            name='created_by',
            field=models.ForeignKey(default=utility.models.get_default_user, on_delete=models.SET(utility.models.get_sentinel_user), to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fieldsample',
            name='field_sample_barcode',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='field_sample_barcode', to='sample_label.samplebarcode'),
        ),
        migrations.AddField(
            model_name='fieldsample',
            name='sample_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='sample_label.sampletype'),
        ),
        migrations.AddField(
            model_name='fieldsample',
            name='survey_global_id',
            field=models.ForeignKey(db_column='survey_global_id', on_delete=django.db.models.deletion.CASCADE, related_name='field_samples', to='field_survey.fieldsurvey'),
        ),
        migrations.AddField(
            model_name='fieldcrew',
            name='created_by',
            field=models.ForeignKey(default=utility.models.get_default_user, on_delete=models.SET(utility.models.get_sentinel_user), to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fieldcrew',
            name='survey_global_id',
            field=models.ForeignKey(db_column='survey_global_id', on_delete=django.db.models.deletion.CASCADE, related_name='field_crew', to='field_survey.fieldsurvey'),
        ),
        migrations.AddField(
            model_name='envmeasuretype',
            name='created_by',
            field=models.ForeignKey(default=utility.models.get_default_user, on_delete=models.SET(utility.models.get_sentinel_user), to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='envmeasure',
            name='created_by',
            field=models.ForeignKey(default=utility.models.get_default_user, on_delete=models.SET(utility.models.get_sentinel_user), to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='envmeasure',
            name='env_measure_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='env_measure_types', to='field_survey.envmeasuretype', verbose_name='Environmental Measurement(s)'),
        ),
        migrations.AddField(
            model_name='envmeasure',
            name='survey_global_id',
            field=models.ForeignKey(db_column='survey_global_id', on_delete=django.db.models.deletion.CASCADE, related_name='env_measurements', to='field_survey.fieldsurvey'),
        ),
        migrations.AddField(
            model_name='subcoresample',
            name='created_by',
            field=models.ForeignKey(default=utility.models.get_default_user, on_delete=models.SET(utility.models.get_sentinel_user), to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subcoresample',
            name='subcore_protocol',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='utility.standardoperatingprocedure', verbose_name='Sub-Core Protocol'),
        ),
        migrations.AddField(
            model_name='filtersample',
            name='created_by',
            field=models.ForeignKey(default=utility.models.get_default_user, on_delete=models.SET(utility.models.get_sentinel_user), to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='filtersample',
            name='filter_protocol',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='utility.standardoperatingprocedure', verbose_name='Filter Protocol'),
        ),
        migrations.AlterUniqueTogether(
            name='envmeasure',
            unique_together={('survey_global_id', 'env_measure_datetime', 'env_measure_type', 'env_measure_value')},
        ),
    ]
