# Generated by Django 4.0.7 on 2026-01-14 16:32

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnvoBiomeFifth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified_datetime', models.DateTimeField(auto_now=True, null=True, verbose_name='Modified DateTime')),
                ('created_datetime', models.DateTimeField(auto_now_add=True, verbose_name='Created DateTime')),
                ('biome_fifth_tier', models.CharField(max_length=255, unique=True, verbose_name='ENVO Biome 5th Tier')),
                ('biome_fifth_tier_slug', models.SlugField(max_length=255, verbose_name='ENVO Biome 5th Tier Slug')),
                ('biome_fourth_tier_slug', models.CharField(max_length=255, verbose_name='ENVO Biome 4th Tier')),
                ('biome_third_tier_slug', models.CharField(max_length=255, verbose_name='ENVO Biome 3rd Tier')),
                ('biome_second_tier_slug', models.CharField(max_length=255, verbose_name='ENVO Biome 2nd Tier')),
                ('biome_first_tier_slug', models.CharField(max_length=255, verbose_name='ENVO Biome 1st Tier')),
                ('envo_identifier', models.CharField(default='[ENVO:00000428]', max_length=255, verbose_name='ENVO Identifier')),
                ('ontology_url', models.URLField(default='http://purl.obolibrary.org/obo/ENVO_00000428', max_length=255, verbose_name='Ontology URL')),
            ],
            options={
                'verbose_name': 'ENVO Biome 5th Tier',
                'verbose_name_plural': 'ENVO Biome 5th Tiers',
            },
        ),
        migrations.CreateModel(
            name='EnvoBiomeFirst',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified_datetime', models.DateTimeField(auto_now=True, null=True, verbose_name='Modified DateTime')),
                ('created_datetime', models.DateTimeField(auto_now_add=True, verbose_name='Created DateTime')),
                ('biome_first_tier', models.CharField(max_length=255, unique=True, verbose_name='ENVO Biome 1st Tier')),
                ('biome_first_tier_slug', models.SlugField(max_length=255, verbose_name='ENVO Biome 1st Tier Slug')),
                ('envo_identifier', models.CharField(default='[ENVO:00000428]', max_length=255, verbose_name='ENVO Identifier')),
                ('ontology_url', models.URLField(default='http://purl.obolibrary.org/obo/ENVO_00000428', max_length=255, verbose_name='Ontology URL')),
            ],
            options={
                'verbose_name': 'ENVO Biome 1st Tier',
                'verbose_name_plural': 'ENVO Biome 1st Tiers',
            },
        ),
        migrations.CreateModel(
            name='EnvoBiomeFourth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified_datetime', models.DateTimeField(auto_now=True, null=True, verbose_name='Modified DateTime')),
                ('created_datetime', models.DateTimeField(auto_now_add=True, verbose_name='Created DateTime')),
                ('biome_fourth_tier', models.CharField(max_length=255, unique=True, verbose_name='ENVO Biome 4th Tier')),
                ('biome_fourth_tier_slug', models.SlugField(max_length=255, verbose_name='ENVO Biome 4th Tier Slug')),
                ('biome_third_tier_slug', models.CharField(max_length=255, verbose_name='ENVO Biome 3rd Tier')),
                ('biome_second_tier_slug', models.CharField(max_length=255, verbose_name='ENVO Biome 2nd Tier')),
                ('biome_first_tier_slug', models.CharField(max_length=255, verbose_name='ENVO Biome 1st Tier')),
                ('envo_identifier', models.CharField(default='[ENVO:00000428]', max_length=255, verbose_name='ENVO Identifier')),
                ('ontology_url', models.URLField(default='http://purl.obolibrary.org/obo/ENVO_00000428', max_length=255, verbose_name='Ontology URL')),
            ],
            options={
                'verbose_name': 'ENVO Biome 4th Tier',
                'verbose_name_plural': 'ENVO Biome 4th Tiers',
            },
        ),
        migrations.CreateModel(
            name='EnvoBiomeSecond',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified_datetime', models.DateTimeField(auto_now=True, null=True, verbose_name='Modified DateTime')),
                ('created_datetime', models.DateTimeField(auto_now_add=True, verbose_name='Created DateTime')),
                ('biome_second_tier', models.CharField(max_length=255, unique=True, verbose_name='ENVO Biome 2nd Tier')),
                ('biome_second_tier_slug', models.SlugField(max_length=255, verbose_name='ENVO Biome 2nd Tier Slug')),
                ('biome_first_tier_slug', models.CharField(max_length=255, verbose_name='ENVO Biome 1st Tier')),
                ('envo_identifier', models.CharField(default='[ENVO:00000428]', max_length=255, verbose_name='ENVO Identifier')),
                ('ontology_url', models.URLField(default='http://purl.obolibrary.org/obo/ENVO_00000428', max_length=255, verbose_name='Ontology URL')),
            ],
            options={
                'verbose_name': 'ENVO Biome 2nd Tier',
                'verbose_name_plural': 'ENVO Biome 2nd Tiers',
            },
        ),
        migrations.CreateModel(
            name='EnvoBiomeThird',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified_datetime', models.DateTimeField(auto_now=True, null=True, verbose_name='Modified DateTime')),
                ('created_datetime', models.DateTimeField(auto_now_add=True, verbose_name='Created DateTime')),
                ('biome_third_tier', models.CharField(max_length=255, unique=True, verbose_name='ENVO Biome 3rd Tier')),
                ('biome_third_tier_slug', models.SlugField(max_length=255, verbose_name='ENVO Biome 3rd Tier Slug')),
                ('biome_second_tier_slug', models.CharField(max_length=255, verbose_name='ENVO Biome 2nd Tier')),
                ('biome_first_tier_slug', models.CharField(max_length=255, verbose_name='ENVO Biome 1st Tier')),
                ('envo_identifier', models.CharField(default='[ENVO:00000428]', max_length=255, verbose_name='ENVO Identifier')),
                ('ontology_url', models.URLField(default='http://purl.obolibrary.org/obo/ENVO_00000428', max_length=255, verbose_name='Ontology URL')),
            ],
            options={
                'verbose_name': 'ENVO Biome 3rd Tier',
                'verbose_name_plural': 'ENVO Biome 3rd Tiers',
            },
        ),
        migrations.CreateModel(
            name='EnvoFeatureFifth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified_datetime', models.DateTimeField(auto_now=True, null=True, verbose_name='Modified DateTime')),
                ('created_datetime', models.DateTimeField(auto_now_add=True, verbose_name='Created DateTime')),
                ('feature_fifth_tier', models.CharField(max_length=255, unique=True, verbose_name='ENVO Feature 5th Tier')),
                ('feature_fifth_tier_slug', models.SlugField(max_length=255, verbose_name='ENVO Feature 5th Tier Slug')),
                ('feature_fourth_tier_slug', models.CharField(max_length=255, verbose_name='ENVO Feature 4th Tier')),
                ('feature_third_tier_slug', models.CharField(max_length=255, verbose_name='ENVO Feature 3rd Tier')),
                ('feature_second_tier_slug', models.CharField(max_length=255, verbose_name='ENVO Feature 2nd Tier')),
                ('feature_first_tier_slug', models.CharField(max_length=255, verbose_name='ENVO Feature 1st Tier')),
                ('envo_identifier', models.CharField(default='[ENVO:01000813]', max_length=255, verbose_name='ENVO Identifier')),
                ('ontology_url', models.URLField(default='http://purl.obolibrary.org/obo/ENVO_01000813', max_length=255, verbose_name='Ontology URL')),
            ],
            options={
                'verbose_name': 'ENVO Feature 5th Tier',
                'verbose_name_plural': 'ENVO Feature 5th Tiers',
            },
        ),
        migrations.CreateModel(
            name='EnvoFeatureFirst',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified_datetime', models.DateTimeField(auto_now=True, null=True, verbose_name='Modified DateTime')),
                ('created_datetime', models.DateTimeField(auto_now_add=True, verbose_name='Created DateTime')),
                ('feature_first_tier', models.CharField(max_length=255, unique=True, verbose_name='ENVO Feature 1st Tier')),
                ('feature_first_tier_slug', models.SlugField(max_length=255, verbose_name='ENVO Feature 1st Tier Slug')),
                ('envo_identifier', models.CharField(default='[ENVO:01000813]', max_length=255, verbose_name='ENVO Identifier')),
                ('ontology_url', models.URLField(default='http://purl.obolibrary.org/obo/ENVO_01000813', max_length=255, verbose_name='Ontology URL')),
            ],
            options={
                'verbose_name': 'ENVO Feature 1st Tier',
                'verbose_name_plural': 'ENVO Feature 1st Tiers',
            },
        ),
        migrations.CreateModel(
            name='EnvoFeatureFourth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified_datetime', models.DateTimeField(auto_now=True, null=True, verbose_name='Modified DateTime')),
                ('created_datetime', models.DateTimeField(auto_now_add=True, verbose_name='Created DateTime')),
                ('feature_fourth_tier', models.CharField(max_length=255, unique=True, verbose_name='ENVO Feature 4th Tier')),
                ('feature_fourth_tier_slug', models.SlugField(max_length=255, verbose_name='ENVO Feature 4th Tier Slug')),
                ('feature_third_tier_slug', models.CharField(max_length=255, verbose_name='ENVO Feature 3rd Tier')),
                ('feature_second_tier_slug', models.CharField(max_length=255, verbose_name='ENVO Feature 2nd Tier')),
                ('feature_first_tier_slug', models.CharField(max_length=255, verbose_name='ENVO Feature 1st Tier')),
                ('envo_identifier', models.CharField(default='[ENVO:01000813]', max_length=255, verbose_name='ENVO Identifier')),
                ('ontology_url', models.URLField(default='http://purl.obolibrary.org/obo/ENVO_01000813', max_length=255, verbose_name='Ontology URL')),
            ],
            options={
                'verbose_name': 'ENVO Feature 4th Tier',
                'verbose_name_plural': 'ENVO Feature 4th Tiers',
            },
        ),
        migrations.CreateModel(
            name='EnvoFeatureSecond',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified_datetime', models.DateTimeField(auto_now=True, null=True, verbose_name='Modified DateTime')),
                ('created_datetime', models.DateTimeField(auto_now_add=True, verbose_name='Created DateTime')),
                ('feature_second_tier', models.CharField(max_length=255, unique=True, verbose_name='ENVO Feature 2nd Tier')),
                ('feature_second_tier_slug', models.SlugField(max_length=255, verbose_name='ENVO Feature 2nd Tier Slug')),
                ('feature_first_tier_slug', models.CharField(max_length=255, verbose_name='ENVO Feature 1st Tier')),
                ('envo_identifier', models.CharField(default='[ENVO:01000813]', max_length=255, verbose_name='ENVO Identifier')),
                ('ontology_url', models.URLField(default='http://purl.obolibrary.org/obo/ENVO_01000813', max_length=255, verbose_name='Ontology URL')),
            ],
            options={
                'verbose_name': 'ENVO Feature 2nd Tier',
                'verbose_name_plural': 'ENVO Feature 2nd Tiers',
            },
        ),
        migrations.CreateModel(
            name='EnvoFeatureSeventh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified_datetime', models.DateTimeField(auto_now=True, null=True, verbose_name='Modified DateTime')),
                ('created_datetime', models.DateTimeField(auto_now_add=True, verbose_name='Created DateTime')),
                ('feature_seventh_tier', models.CharField(max_length=255, unique=True, verbose_name='ENVO Feature 7th Tier ')),
                ('feature_seventh_tier_slug', models.SlugField(max_length=255, verbose_name='ENVO Feature 7th Tier Slug')),
                ('feature_sixth_tier_slug', models.CharField(max_length=255, verbose_name='ENVO Feature 6th Tier')),
                ('feature_fifth_tier_slug', models.CharField(max_length=255, verbose_name='ENVO Feature 5th Tier')),
                ('feature_fourth_tier_slug', models.CharField(max_length=255, verbose_name='ENVO Feature 4th Tier')),
                ('feature_third_tier_slug', models.CharField(max_length=255, verbose_name='ENVO Feature 3rd Tier')),
                ('feature_second_tier_slug', models.CharField(max_length=255, verbose_name='ENVO Feature 2nd Tier')),
                ('feature_first_tier_slug', models.CharField(max_length=255, verbose_name='ENVO Feature 1st Tier')),
                ('envo_identifier', models.CharField(default='[ENVO:01000813]', max_length=255, verbose_name='ENVO Identifier')),
                ('ontology_url', models.URLField(default='http://purl.obolibrary.org/obo/ENVO_01000813', max_length=255, verbose_name='Ontology URL')),
            ],
            options={
                'verbose_name': 'ENVO Feature 7th Tier',
                'verbose_name_plural': 'ENVO Feature 7th Tiers',
            },
        ),
        migrations.CreateModel(
            name='EnvoFeatureSixth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified_datetime', models.DateTimeField(auto_now=True, null=True, verbose_name='Modified DateTime')),
                ('created_datetime', models.DateTimeField(auto_now_add=True, verbose_name='Created DateTime')),
                ('feature_sixth_tier', models.CharField(max_length=255, unique=True, verbose_name='ENVO Feature 6th Tier')),
                ('feature_sixth_tier_slug', models.SlugField(max_length=255, verbose_name='ENVO Feature 6th Tier Slug')),
                ('feature_fifth_tier_slug', models.CharField(max_length=255, verbose_name='ENVO Feature 5th Tier')),
                ('feature_fourth_tier_slug', models.CharField(max_length=255, verbose_name='ENVO Feature 4th Tier')),
                ('feature_third_tier_slug', models.CharField(max_length=255, verbose_name='ENVO Feature 3rd Tier')),
                ('feature_second_tier_slug', models.CharField(max_length=255, verbose_name='ENVO Feature 2nd Tier')),
                ('feature_first_tier_slug', models.CharField(max_length=255, verbose_name='ENVO Feature 1st Tier')),
                ('envo_identifier', models.CharField(default='[ENVO:01000813]', max_length=255, verbose_name='ENVO Identifier')),
                ('ontology_url', models.URLField(default='http://purl.obolibrary.org/obo/ENVO_01000813', max_length=255, verbose_name='Ontology URL')),
            ],
            options={
                'verbose_name': 'ENVO Feature 6th Tier',
                'verbose_name_plural': 'ENVO Feature 6th Tiers',
            },
        ),
        migrations.CreateModel(
            name='EnvoFeatureThird',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified_datetime', models.DateTimeField(auto_now=True, null=True, verbose_name='Modified DateTime')),
                ('created_datetime', models.DateTimeField(auto_now_add=True, verbose_name='Created DateTime')),
                ('feature_third_tier', models.CharField(max_length=255, unique=True, verbose_name='ENVO Feature 3rd Tier')),
                ('feature_third_tier_slug', models.SlugField(max_length=255, verbose_name='ENVO Feature 3rd Tier Slug')),
                ('feature_second_tier_slug', models.CharField(max_length=255, verbose_name='ENVO Feature 2nd Tier')),
                ('feature_first_tier_slug', models.CharField(max_length=255, verbose_name='ENVO Feature 1st Tier')),
                ('envo_identifier', models.CharField(default='[ENVO:01000813]', max_length=255, verbose_name='ENVO Identifier')),
                ('ontology_url', models.URLField(default='http://purl.obolibrary.org/obo/ENVO_01000813', max_length=255, verbose_name='Ontology URL')),
            ],
            options={
                'verbose_name': 'ENVO Feature 3rd Tier',
                'verbose_name_plural': 'ENVO Feature 3rd Tiers',
            },
        ),
        migrations.CreateModel(
            name='FieldSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified_datetime', models.DateTimeField(auto_now=True, null=True, verbose_name='Modified DateTime')),
                ('created_datetime', models.DateTimeField(auto_now_add=True, verbose_name='Created DateTime')),
                ('site_id', models.CharField(max_length=255, unique=True, verbose_name='Site ID')),
                ('general_location_name', models.CharField(max_length=255, null=True, verbose_name='Location')),
                ('purpose', models.CharField(max_length=255, verbose_name='Site Description/Purpose')),
                ('country_code', models.CharField(max_length=6, verbose_name='Country code')),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='Latitude, Longitude (DD WGS84)')),
                ('watershed_type', models.CharField(blank=True, choices=[(None, '(Unknown)'), ('coastal', 'Coastal'), ('riverine', 'Riverine'), ('lacustrine', 'Lacustrine'), ('estuarine', 'Estuarine'), ('wetland', 'Wetland'), ('urban', 'Urban'), ('agricultural', 'Agricultural'), ('forested', 'Forested')], max_length=50, verbose_name='Watershed Type')),
            ],
            options={
                'verbose_name': 'Field Site',
                'verbose_name_plural': 'Field Sites',
            },
        ),
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified_datetime', models.DateTimeField(auto_now=True, null=True, verbose_name='Modified DateTime')),
                ('created_datetime', models.DateTimeField(auto_now_add=True, verbose_name='Created DateTime')),
                ('system_code', models.SlugField(max_length=1, unique=True, verbose_name='System Code')),
                ('system_label', models.CharField(max_length=255, verbose_name='System Label')),
            ],
            options={
                'verbose_name': 'System',
                'verbose_name_plural': 'Systems',
            },
        ),
        migrations.CreateModel(
            name='Watershed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified_datetime', models.DateTimeField(auto_now=True, null=True, verbose_name='Modified DateTime')),
                ('created_datetime', models.DateTimeField(auto_now_add=True, verbose_name='Created DateTime')),
                ('watershed_code', models.SlugField(max_length=3, unique=True, verbose_name='Watershed Code')),
                ('watershed_label', models.CharField(max_length=255, verbose_name='Watershed Label')),
                ('huc8', models.CharField(max_length=255, verbose_name='HUC8')),
                ('states', models.CharField(max_length=255, verbose_name='States')),
                ('lat', models.DecimalField(decimal_places=16, max_digits=22, verbose_name='Latitude (DD)')),
                ('lon', models.DecimalField(decimal_places=16, max_digits=22, verbose_name='Longitude (DD)')),
                ('area_sqkm', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Area (sqkm)')),
                ('area_acres', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Area (acres)')),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
            options={
                'verbose_name': 'Watershed',
                'verbose_name_plural': 'Watersheds',
            },
        ),
        migrations.CreateModel(
            name='WorldBorder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('area', models.IntegerField()),
                ('pop2005', models.IntegerField(verbose_name='Population 2005')),
                ('fips', models.CharField(blank=True, max_length=2, verbose_name='FIPS Code')),
                ('iso2', models.CharField(max_length=2, verbose_name='2 Digit ISO')),
                ('iso3', models.CharField(max_length=3, verbose_name='3 Digit ISO')),
                ('un', models.IntegerField(verbose_name='United Nations Code')),
                ('region', models.IntegerField(verbose_name='Region Code')),
                ('subregion', models.IntegerField(verbose_name='Sub-Region Code')),
                ('lon', models.DecimalField(decimal_places=16, max_digits=22)),
                ('lat', models.DecimalField(decimal_places=16, max_digits=22)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
            options={
                'verbose_name': 'World Border',
                'verbose_name_plural': 'World Borders',
            },
        ),
    ]
