# Generated by Django 4.0.7 on 2026-01-14 16:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import utility.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('utility', '0001_initial'),
        ('field_site', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='watershed',
            name='created_by',
            field=models.ForeignKey(default=utility.models.get_default_user, on_delete=models.SET(utility.models.get_sentinel_user), to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='system',
            name='created_by',
            field=models.ForeignKey(default=utility.models.get_default_user, on_delete=models.SET(utility.models.get_sentinel_user), to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fieldsite',
            name='created_by',
            field=models.ForeignKey(default=utility.models.get_default_user, on_delete=models.SET(utility.models.get_sentinel_user), to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fieldsite',
            name='envo_biome_fifth',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='biome_fifth', to='field_site.envobiomefifth'),
        ),
        migrations.AddField(
            model_name='fieldsite',
            name='envo_biome_first',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='biome_first', to='field_site.envobiomefirst'),
        ),
        migrations.AddField(
            model_name='fieldsite',
            name='envo_biome_fourth',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='biome_fourth', to='field_site.envobiomefourth'),
        ),
        migrations.AddField(
            model_name='fieldsite',
            name='envo_biome_second',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='biome_second', to='field_site.envobiomesecond'),
        ),
        migrations.AddField(
            model_name='fieldsite',
            name='envo_biome_third',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='biome_third', to='field_site.envobiomethird'),
        ),
        migrations.AddField(
            model_name='fieldsite',
            name='envo_feature_fifth',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='feature_fifth', to='field_site.envofeaturefifth'),
        ),
        migrations.AddField(
            model_name='fieldsite',
            name='envo_feature_first',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='feature_first', to='field_site.envofeaturefirst'),
        ),
        migrations.AddField(
            model_name='fieldsite',
            name='envo_feature_fourth',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='feature_fourth', to='field_site.envofeaturefourth'),
        ),
        migrations.AddField(
            model_name='fieldsite',
            name='envo_feature_second',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='feature_second', to='field_site.envofeaturesecond'),
        ),
        migrations.AddField(
            model_name='fieldsite',
            name='envo_feature_seventh',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='feature_seventh', to='field_site.envofeatureseventh'),
        ),
        migrations.AddField(
            model_name='fieldsite',
            name='envo_feature_sixth',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='feature_sixth', to='field_site.envofeaturesixth'),
        ),
        migrations.AddField(
            model_name='fieldsite',
            name='envo_feature_third',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='feature_third', to='field_site.envofeaturethird'),
        ),
        migrations.AddField(
            model_name='fieldsite',
            name='project',
            field=models.ManyToManyField(blank=True, related_name='projects', to='utility.project', verbose_name='Affiliated Project(s)'),
        ),
        migrations.AddField(
            model_name='envofeaturethird',
            name='created_by',
            field=models.ForeignKey(default=utility.models.get_default_user, on_delete=models.SET(utility.models.get_sentinel_user), to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='envofeaturethird',
            name='feature_second_tier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='field_site.envofeaturesecond'),
        ),
        migrations.AddField(
            model_name='envofeaturesixth',
            name='created_by',
            field=models.ForeignKey(default=utility.models.get_default_user, on_delete=models.SET(utility.models.get_sentinel_user), to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='envofeaturesixth',
            name='feature_fifth_tier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='field_site.envofeaturefifth'),
        ),
        migrations.AddField(
            model_name='envofeatureseventh',
            name='created_by',
            field=models.ForeignKey(default=utility.models.get_default_user, on_delete=models.SET(utility.models.get_sentinel_user), to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='envofeatureseventh',
            name='feature_sixth_tier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='field_site.envofeaturesixth'),
        ),
        migrations.AddField(
            model_name='envofeaturesecond',
            name='created_by',
            field=models.ForeignKey(default=utility.models.get_default_user, on_delete=models.SET(utility.models.get_sentinel_user), to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='envofeaturesecond',
            name='feature_first_tier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='field_site.envofeaturefirst'),
        ),
        migrations.AddField(
            model_name='envofeaturefourth',
            name='created_by',
            field=models.ForeignKey(default=utility.models.get_default_user, on_delete=models.SET(utility.models.get_sentinel_user), to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='envofeaturefourth',
            name='feature_third_tier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='field_site.envofeaturethird'),
        ),
        migrations.AddField(
            model_name='envofeaturefirst',
            name='created_by',
            field=models.ForeignKey(default=utility.models.get_default_user, on_delete=models.SET(utility.models.get_sentinel_user), to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='envofeaturefifth',
            name='created_by',
            field=models.ForeignKey(default=utility.models.get_default_user, on_delete=models.SET(utility.models.get_sentinel_user), to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='envofeaturefifth',
            name='feature_fourth_tier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='field_site.envofeaturefourth'),
        ),
        migrations.AddField(
            model_name='envobiomethird',
            name='biome_second_tier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='field_site.envobiomesecond'),
        ),
        migrations.AddField(
            model_name='envobiomethird',
            name='created_by',
            field=models.ForeignKey(default=utility.models.get_default_user, on_delete=models.SET(utility.models.get_sentinel_user), to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='envobiomesecond',
            name='biome_first_tier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='field_site.envobiomefirst'),
        ),
        migrations.AddField(
            model_name='envobiomesecond',
            name='created_by',
            field=models.ForeignKey(default=utility.models.get_default_user, on_delete=models.SET(utility.models.get_sentinel_user), to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='envobiomefourth',
            name='biome_third_tier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='field_site.envobiomethird'),
        ),
        migrations.AddField(
            model_name='envobiomefourth',
            name='created_by',
            field=models.ForeignKey(default=utility.models.get_default_user, on_delete=models.SET(utility.models.get_sentinel_user), to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='envobiomefirst',
            name='created_by',
            field=models.ForeignKey(default=utility.models.get_default_user, on_delete=models.SET(utility.models.get_sentinel_user), to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='envobiomefifth',
            name='biome_fourth_tier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='field_site.envobiomefourth'),
        ),
        migrations.AddField(
            model_name='envobiomefifth',
            name='created_by',
            field=models.ForeignKey(default=utility.models.get_default_user, on_delete=models.SET(utility.models.get_sentinel_user), to=settings.AUTH_USER_MODEL),
        ),
    ]
