# Generated by Django 4.0.7 on 2026-01-14 16:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import utility.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('utility', '0001_initial'),
        ('bioinformatics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wet_lab', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxonsupergroup',
            name='created_by',
            field=models.ForeignKey(default=utility.models.get_default_user, on_delete=models.SET(utility.models.get_sentinel_user), to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='taxonsupergroup',
            name='taxon_kingdom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='bioinformatics.taxonkingdom'),
        ),
        migrations.AddField(
            model_name='taxonspecies',
            name='created_by',
            field=models.ForeignKey(default=utility.models.get_default_user, on_delete=models.SET(utility.models.get_sentinel_user), to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='taxonspecies',
            name='taxon_genus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='bioinformatics.taxongenus'),
        ),
        migrations.AddField(
            model_name='taxonphylumdivision',
            name='created_by',
            field=models.ForeignKey(default=utility.models.get_default_user, on_delete=models.SET(utility.models.get_sentinel_user), to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='taxonphylumdivision',
            name='taxon_supergroup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='bioinformatics.taxonsupergroup'),
        ),
        migrations.AddField(
            model_name='taxonorder',
            name='created_by',
            field=models.ForeignKey(default=utility.models.get_default_user, on_delete=models.SET(utility.models.get_sentinel_user), to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='taxonorder',
            name='taxon_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='bioinformatics.taxonclass'),
        ),
        migrations.AddField(
            model_name='taxonomicannotation',
            name='annotation_metadata',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='bioinformatics.annotationmetadata'),
        ),
        migrations.AddField(
            model_name='taxonomicannotation',
            name='created_by',
            field=models.ForeignKey(default=utility.models.get_default_user, on_delete=models.SET(utility.models.get_sentinel_user), to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='taxonomicannotation',
            name='feature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='bioinformatics.featureoutput'),
        ),
        migrations.AddField(
            model_name='taxonomicannotation',
            name='manual_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='manual_class', to='bioinformatics.taxonclass'),
        ),
        migrations.AddField(
            model_name='taxonomicannotation',
            name='manual_domain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='manual_domain', to='bioinformatics.taxondomain'),
        ),
        migrations.AddField(
            model_name='taxonomicannotation',
            name='manual_family',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='manual_family', to='bioinformatics.taxonfamily'),
        ),
        migrations.AddField(
            model_name='taxonomicannotation',
            name='manual_genus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='manual_genus', to='bioinformatics.taxongenus'),
        ),
        migrations.AddField(
            model_name='taxonomicannotation',
            name='manual_kingdom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='manual_kingdom', to='bioinformatics.taxonkingdom'),
        ),
        migrations.AddField(
            model_name='taxonomicannotation',
            name='manual_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='manual_order', to='bioinformatics.taxonorder'),
        ),
        migrations.AddField(
            model_name='taxonomicannotation',
            name='manual_phylum_division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='manual_phylum_division', to='bioinformatics.taxonphylumdivision'),
        ),
        migrations.AddField(
            model_name='taxonomicannotation',
            name='manual_species',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='manual_species', to='bioinformatics.taxonspecies'),
        ),
        migrations.AddField(
            model_name='taxonomicannotation',
            name='manual_supergroup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='manual_supergroup', to='bioinformatics.taxonsupergroup'),
        ),
        migrations.AddField(
            model_name='taxonomicannotation',
            name='reference_database',
            field=models.ManyToManyField(related_name='reference_databases', to='bioinformatics.referencedatabase', verbose_name='Reference Databases'),
        ),
        migrations.AddField(
            model_name='taxonkingdom',
            name='created_by',
            field=models.ForeignKey(default=utility.models.get_default_user, on_delete=models.SET(utility.models.get_sentinel_user), to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='taxonkingdom',
            name='taxon_domain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='bioinformatics.taxondomain'),
        ),
        migrations.AddField(
            model_name='taxongenus',
            name='created_by',
            field=models.ForeignKey(default=utility.models.get_default_user, on_delete=models.SET(utility.models.get_sentinel_user), to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='taxongenus',
            name='taxon_family',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='bioinformatics.taxonfamily'),
        ),
        migrations.AddField(
            model_name='taxonfamily',
            name='created_by',
            field=models.ForeignKey(default=utility.models.get_default_user, on_delete=models.SET(utility.models.get_sentinel_user), to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='taxonfamily',
            name='taxon_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='bioinformatics.taxonorder'),
        ),
        migrations.AddField(
            model_name='taxondomain',
            name='created_by',
            field=models.ForeignKey(default=utility.models.get_default_user, on_delete=models.SET(utility.models.get_sentinel_user), to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='taxonclass',
            name='created_by',
            field=models.ForeignKey(default=utility.models.get_default_user, on_delete=models.SET(utility.models.get_sentinel_user), to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='taxonclass',
            name='taxon_phylum_division',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='bioinformatics.taxonphylumdivision'),
        ),
        migrations.AddField(
            model_name='referencedatabase',
            name='created_by',
            field=models.ForeignKey(default=utility.models.get_default_user, on_delete=models.SET(utility.models.get_sentinel_user), to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='qualitymetadata',
            name='analysis_sop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='utility.standardoperatingprocedure', verbose_name='Analysis SOP'),
        ),
        migrations.AddField(
            model_name='qualitymetadata',
            name='created_by',
            field=models.ForeignKey(default=utility.models.get_default_user, on_delete=models.SET(utility.models.get_sentinel_user), to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='qualitymetadata',
            name='fastq_file',
            field=models.ManyToManyField(related_name='fastq_files', to='wet_lab.fastqfile', verbose_name='FASTQ Files'),
        ),
        migrations.AddField(
            model_name='qualitymetadata',
            name='process_location',
            field=models.ForeignKey(default=utility.models.get_default_process_location, on_delete=django.db.models.deletion.RESTRICT, to='utility.processlocation'),
        ),
        migrations.AddField(
            model_name='featureread',
            name='created_by',
            field=models.ForeignKey(default=utility.models.get_default_user, on_delete=models.SET(utility.models.get_sentinel_user), to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='featureread',
            name='extraction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='wet_lab.extraction'),
        ),
        migrations.AddField(
            model_name='featureread',
            name='feature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='bioinformatics.featureoutput'),
        ),
        migrations.AddField(
            model_name='featureoutput',
            name='created_by',
            field=models.ForeignKey(default=utility.models.get_default_user, on_delete=models.SET(utility.models.get_sentinel_user), to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='featureoutput',
            name='denoise_cluster_metadata',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='bioinformatics.denoiseclustermetadata'),
        ),
        migrations.AddField(
            model_name='denoiseclustermethod',
            name='created_by',
            field=models.ForeignKey(default=utility.models.get_default_user, on_delete=models.SET(utility.models.get_sentinel_user), to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='denoiseclustermetadata',
            name='analysis_sop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='utility.standardoperatingprocedure', verbose_name='Analysis SOP'),
        ),
        migrations.AddField(
            model_name='denoiseclustermetadata',
            name='created_by',
            field=models.ForeignKey(default=utility.models.get_default_user, on_delete=models.SET(utility.models.get_sentinel_user), to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='denoiseclustermetadata',
            name='denoise_cluster_method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='bioinformatics.denoiseclustermethod'),
        ),
        migrations.AddField(
            model_name='denoiseclustermetadata',
            name='process_location',
            field=models.ForeignKey(default=utility.models.get_default_process_location, on_delete=django.db.models.deletion.RESTRICT, to='utility.processlocation'),
        ),
        migrations.AddField(
            model_name='denoiseclustermetadata',
            name='quality_metadata',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='bioinformatics.qualitymetadata'),
        ),
        migrations.AddField(
            model_name='annotationmethod',
            name='created_by',
            field=models.ForeignKey(default=utility.models.get_default_user, on_delete=models.SET(utility.models.get_sentinel_user), to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='annotationmetadata',
            name='analysis_sop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='utility.standardoperatingprocedure', verbose_name='Analysis SOP'),
        ),
        migrations.AddField(
            model_name='annotationmetadata',
            name='annotation_method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='bioinformatics.annotationmethod'),
        ),
        migrations.AddField(
            model_name='annotationmetadata',
            name='created_by',
            field=models.ForeignKey(default=utility.models.get_default_user, on_delete=models.SET(utility.models.get_sentinel_user), to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='annotationmetadata',
            name='denoise_cluster_metadata',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='bioinformatics.denoiseclustermetadata'),
        ),
        migrations.AddField(
            model_name='annotationmetadata',
            name='process_location',
            field=models.ForeignKey(default=utility.models.get_default_process_location, on_delete=django.db.models.deletion.RESTRICT, to='utility.processlocation'),
        ),
        migrations.AlterUniqueTogether(
            name='referencedatabase',
            unique_together={('refdb_name', 'refdb_version')},
        ),
        migrations.AlterUniqueTogether(
            name='denoiseclustermethod',
            unique_together={('denoise_cluster_method_name', 'denoise_cluster_method_software_package')},
        ),
        migrations.AlterUniqueTogether(
            name='annotationmethod',
            unique_together={('annotation_method_name', 'annotation_method_software_package')},
        ),
    ]
